#!/usr/bin/env python3
"""Embed text files as a C table of setup_template_file_t (see simulator/src/setup_dir.h).

Usage: embed_files.py OUTPUT.c INPUT...  -- each entry is named after the input's basename.
"""
import os
import sys


def c_string(text):
    out = []
    for line in text.splitlines(keepends=True):
        escaped = line.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n")
        out.append(f'        "{escaped}"')
    return "\n".join(out) if out else '        ""'


def main():
    output, inputs = sys.argv[1], sys.argv[2:]
    entries = []
    for path in inputs:
        with open(path, encoding="utf-8") as f:
            entries.append(f'    {{"{os.path.basename(path)}",\n{c_string(f.read())}}},')
    with open(output, "w", encoding="utf-8") as f:
        f.write("/* Generated by simulator/scripts/embed_files.py -- do not edit. */\n")
        f.write('#include "setup_dir.h"\n\n')
        f.write("const setup_template_file_t setup_template_files[] = {\n")
        f.write("\n".join(entries))
        f.write("\n};\n\n")
        f.write(f"const size_t setup_template_file_count = {len(entries)};\n")


if __name__ == "__main__":
    main()
