schema_version: 1
instance_id: "sim_instance_002"
scenario_file: "simulator/scenarios/test_scenario_001.json"
log_path: "logs/instance_002.log"
receivers:
  - receiver_id: 0
    rest_bind_host: "127.0.0.1"
    rest_port: 8110
    udp_output_host: "127.0.0.1"
    frequency_start_hz: 9960000000
    frequency_stop_hz: 10040000000
    bandwidth_hz: 80000000
    sample_rate_hz: 98304000
    scan_rate_hz_per_s: 100000000000
    udp_80mhz_output_port: 50100
    ddc:
      - ddc_id: 0
        center_frequency_hz: 10005000000
        bandwidth_hz: 20000000
        sample_rate_hz: 24576000
        udp_output_port: 50101
      - ddc_id: 1
        center_frequency_hz: 10010000000
        bandwidth_hz: 20000000
        sample_rate_hz: 24576000
        udp_output_port: 50102
      - ddc_id: 2
        center_frequency_hz: 9995000000
        bandwidth_hz: 20000000
        sample_rate_hz: 24576000
        udp_output_port: 50103
      - ddc_id: 3
        center_frequency_hz: 10030000000
        bandwidth_hz: 20000000
        sample_rate_hz: 24576000
        udp_output_port: 50104
